CREATE TABLE cat (ID SERIAL PRIMARY KEY ,NAME  VARCHAR(255) NOT NULL);
CREATE TABLE prod (
  ID       SERIAL PRIMARY KEY,
  CAT_ID   int NOT NULL REFERENCES cat(id),
  NAME     VARCHAR(255) NOT NULL,
  PRICE    NUMERIC(16,2) NOT NULL
);


